# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]            #/選單一
    name = "貼文"
#    pre = "substack"
    pageRef = "Posts"
    weight = 10

[[main]]
    name = "數學"
#  parent = "Parent"
    pageRef = "Posts/Math"
    weight = 20

[[main]]
    name = "中華文化"
    pageRef = "Posts/Chinese"
    weight = 30

[[main]]
    name = "程式設定"
#  parent = "Parent"
    pageRef = "Posts/Program_Language"
    weight = 40

[[main]]
    name = "程式語言"
#  parent = "Parent"
    pageRef = "Posts/Program_setting"
    weight = 50

#[[subnavigation]]       #/ Posts 子選單一
#    name = "中華文化"   #/選單名稱
#    pageRef = "Posts/Chinese"   #/ 資料夾位置
#    weight = 10     #/ 選單權重

#[[subnavigation]]       #/ Posts 子選單二
#    name = "程式語言"
#   pre = "github"  #/ 圖標設定
#    pageRef = "Posts/Program_Language"
#    weight = 20

#[[subnavigation]]       #/ Posts 子選單三
#    name = "程式設定"
#   pre = "github"
#    pageRef = "Posts/Program_setting"
 #   weight = 30

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
